version: 0.0

os: linux

files:
  - source: deploy
    destination: /home/ubuntu/nodeapp

hooks:
  ApplicationStop:
    - location: deploy/scripts/ApplicationStop.sh
      timeout: 30
      runas: ubuntu

  BeforeInstall:
    - location: deploy/scripts/BeforeInstall.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: deploy/scripts/AfterInstall.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: deploy/scripts/ApplicationStart.sh
      timeout: 60
      runas: ubuntu
