version: 0.0

os: linux

hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 30
      runas: ubuntu

  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 60
      runas: ubuntu
